Repository: plone.app.upgrade


Branch: refs/heads/master
Date: 2017-04-26T15:34:50+02:00
Author: Johannes Raggam (thet) <thetetet@gmail.com>
Commit: https://github.com/plone/plone.app.upgrade/commit/2e1b4207fb53bea4079cf475368acf0406edc2e0

Fix and AttributeError for the Plone 5.1 beta 4 upgrade.

Files changed:
M CHANGES.rst
M plone/app/upgrade/v51/betas.py

diff --git a/CHANGES.rst b/CHANGES.rst
index f5cba07..cd75ba1 100644
--- a/CHANGES.rst
+++ b/CHANGES.rst
@@ -14,7 +14,8 @@ New features:
 
 Bug fixes:
 
-- *add item here*
+- Fix and ``AttributeError`` for the Plone 5.1 beta 4 upgrade.
+  [thet]
 
 
 2.0.3 (2017-04-18)
diff --git a/plone/app/upgrade/v51/betas.py b/plone/app/upgrade/v51/betas.py
index 40b1646..dad633d 100644
--- a/plone/app/upgrade/v51/betas.py
+++ b/plone/app/upgrade/v51/betas.py
@@ -155,12 +155,16 @@ def reindex_mime_type(context):
     cnt = 0
     for brain in zcatalog.unrestrictedSearchResults(object_provides=ifaces):
         obj = brain._unrestrictedGetObject()
+        if not obj:
+            continue
         # First get the new value:
         new_value = ''
         try:  # Dexterity
             new_value = obj.content_type()
         except TypeError:  # Archetypes
             new_value = obj.content_type
+        except AttributeError:
+            continue
         # We can now update the record with the new mime_type value
         record = list(catalog.data[brain.getRID()])
         record[metadata_index] = new_value


Repository: plone.app.upgrade


Branch: refs/heads/master
Date: 2017-04-28T13:29:55+02:00
Author: Jens W. Klein (jensens) <jk@kleinundpartner.at>
Commit: https://github.com/plone/plone.app.upgrade/commit/8afc6f92b5f64eb96392f6ad98c155a52d858e0c

Merge pull request #117 from plone/thet-fix-attrerror51b

Fix and AttributeError for the Plone 5.1 beta 4 upgrade.

Files changed:
M CHANGES.rst
M plone/app/upgrade/v51/betas.py

diff --git a/CHANGES.rst b/CHANGES.rst
index f5cba07..cd75ba1 100644
--- a/CHANGES.rst
+++ b/CHANGES.rst
@@ -14,7 +14,8 @@ New features:
 
 Bug fixes:
 
-- *add item here*
+- Fix and ``AttributeError`` for the Plone 5.1 beta 4 upgrade.
+  [thet]
 
 
 2.0.3 (2017-04-18)
diff --git a/plone/app/upgrade/v51/betas.py b/plone/app/upgrade/v51/betas.py
index 40b1646..dad633d 100644
--- a/plone/app/upgrade/v51/betas.py
+++ b/plone/app/upgrade/v51/betas.py
@@ -155,12 +155,16 @@ def reindex_mime_type(context):
     cnt = 0
     for brain in zcatalog.unrestrictedSearchResults(object_provides=ifaces):
         obj = brain._unrestrictedGetObject()
+        if not obj:
+            continue
         # First get the new value:
         new_value = ''
         try:  # Dexterity
             new_value = obj.content_type()
         except TypeError:  # Archetypes
             new_value = obj.content_type
+        except AttributeError:
+            continue
         # We can now update the record with the new mime_type value
         record = list(catalog.data[brain.getRID()])
         record[metadata_index] = new_value


